### ISSUE TITLE
Upcoming Deprecation: `user_info().filename`

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#879] opened 2024-08-25 16:30 UTC
Found in this the logs on `apps-test`:

> DEPRECATION WARNING: in a future version, the user_info() function will not support the attribute filename. Use current_context().filename instead.

Link to the warning in Docassemble: https://github.com/jhpyle/docassemble/blob/45116d2933e24543ed2e0903f4ee446d9ca7b785/docassemble_base/docassemble/base/functions.py#L851  [The commit](https://github.com/jhpyle/docassemble/commit/f2d15f460738ffd951fe359aa6febb4f9f965772) that makes the change just says "deprecated parts of `user_info()` that did not relate to the user."

All of the places we use `user_info().filename` in projects:

https://github.com/search?q=org%3ASuffolkLITLab%20user_info().filename&type=code

**Comment by nonprofittechy** [comment] 2024-08-28 19:19
Closing as duplicate of #820 but looking at the time, maybe we can safely convert now. I did not want to rush people to upgrade but 6 months might be enough!

**Closed** 2024-08-28 19:20 UTC
Labels: duplicate
