### ISSUE TITLE
Root cause analysis - server crash

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#752] opened 2023-08-28 15:18 UTC
![image](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/assets/7645641/c280db2a-43c0-46bc-ad29-ff69b34f0643)

![image](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/assets/7645641/bd6f8bcb-bb9e-453d-8332-5ba027ca628e)

**Comment by BryceStevenWilley** [comment] 2023-08-28 17:52
After having the chance to look into this more, it actually might the OCR.

The command that took > 10 minutes of 100% CPU was:

```bash
pdftoppm -r 300 -png /tm/files/49.../file.pdf /tmp/files/49.../filepage
```

Started by [this function in docassemble/base/util.py](https://github.com/jhpyle/docassemble/blob/8726242cfbe3a15cad610dc2b518346be68ab142/docassemble_base/docassemble/base/util.py#L10022). On my machine (running on the same input file that seems to have caused the crash) this takes 2 minutes 15 seconds of 100% cpu.

Notably, the resolution passed in 300 DPI, which is pretty high; the only time that the resolution is that high is when you call `DAFile._make_pdf_thumbnail(..., both_formats=True)`, which happens [in the middle of `ocr_finalize`](https://github.com/jhpyle/docassemble/blob/8726242cfbe3a15cad610dc2b518346be68ab142/docassemble_base/docassemble/base/util.py#L9876) and [at the end of `ocr_pdf`](https://github.com/jhpyle/docassemble/blob/8726242cfbe3a15cad610dc2b518346be68ab142/docassemble_base/docassemble/base/util.py#L10133) (why at the end?! It's already called tesseract?). So it's definitely OCR.

I'm looking through our ALExhibit classes now to see what could be going wrong; if you don't pass an `auto_ocr` parameter, it shouldn't do any OCR stuff, but there might be a bug in that initialization, I'm checking for that issue now.

**Comment by nonprofittechy** [comment] 2023-08-28 17:58
Also remember we had ocrmypdf turned off on the production server; I just turned that back on. So this might be mooted?

**Comment by BryceStevenWilley** [comment] 2023-08-28 18:53
Gotcha, that slipped my mind already, thanks.

It was DA native OCR that's causing the issue, [our OCR task](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/59456da209973de9f2727d5fddb0f0ff45b3abfe/docassemble/AssemblyLine/al_document.py#L1745-L1777) doesn't call any of those DA functions that were showing up in the stacktrace last night.

I can reproduce the initial 504 on my machine consistently, and but the `auto_ocr` param seems to be set correct that I can tell.

It seems like my earlier assertion about `both_formats=True` was incorrect; both formats seem to be generating, but what's actually happening is in this stacktrace (generated manually, not with an exception):

```
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8130, in index     interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8414, in assemble     exec_with_trap(question, user_dict)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9846, in exec_with_trap     exec(the_question.compute, the_dict)   
 File "<code block>", line 33, in <module>   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2162, in gather     self._validate(item_object_type, complete_attribute)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2119, in _validate     complex_getattr(elem, attrib)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 10221, in complex_getattr     return getattr(obj, parts[0])   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/AssemblyLine/al_document.py", line 1864, in complete     self.pages.gather()   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2162, in gather     self._validate(item_object_type, complete_attribute)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2121, in _validate     str(elem)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 4136, in __str__     return str(self.show())   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 4676, in show     self.page_path(1, 'page')   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 4631, in page_path     server.fg_make_png_for_pdf(self, prefix, page=page)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 4298, in fg_make_png_for_pdf     docassemble.base.util.make_png_for_pdf(doc, prefix, resolution, PDFTOPPM_COMMAND, page=page)   
 File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 10018, in make_png_for_pdf     make_png_for_pdf_path(path, prefix, resolution, pdf_to_ppm, page=page)   
```

Which still uses the `page` parameter, which causes the dpi of 300 and the long wait. I can't tell why 3 processes are being started, but this does seem like an upstream issue.

**Comment by BryceStevenWilley** [comment] 2023-08-28 19:29
Also uploading the CPU graph: 

![Screenshot from 2023-08-28 15-27-37](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/assets/6252212/112189d3-ab28-42e2-a8f0-4dff144cd215)

**Comment by BryceStevenWilley** [comment] 2023-08-29 02:23
Notable clips from a conversation with Jonathan on Slack:

> Normally docassemble does not call `.show()` on each item in a DAFileList. It looks like this is happening because you are calling .reset_gathered() and .gather() on it. If a .complete_attribute is not set, a list is gathered by calling str() on each item in the list, which for a DAFile causes .show() to be called.

We can avoid this by setting `x[0].pages.complete_attribute = 'ok'`, which is always defined for DAFiles.

So that should fix the fact that a 504 appears right after uploading files. However, I don't think it would fix the entirety of this issue, which was caused by a whole lot of CPU. `pdftoppm` at 300 DPI is just a lot. I think a patch for the moment would be to set `png resolution` in the config to something lower than 300, maybe 200 or 150. Longer term, we should look into generating a JPG instead which would be a bit smaller, and seeing if there's an faster / more efficient version of `pdftoppm` out there.

I'll close this if we think setting `png resolution` to 200 is a good idea, and we do it on all of our servers.

**Comment by nonprofittechy** [comment] 2023-08-29 02:53
OCR does require a pretty high res image for accuracy, I'm assuming that's why 300 dpi is the default. But it shouldn't need to be that high res for a preview thumbnail. Is the issue that it's serving a double purpose?

I'm fine with changing this threshold.

**Comment by BryceStevenWilley** [comment] 2023-08-29 03:14
OCR isn't happening at all. Docassemble uses the 300 DPI image for embedding in any document, so it's always being generated. It's better to do it in the background, and it feel better making something that has less of a compute burden. I guess it only crashed the server when something went wrong (the S3 part of this root cause that we couldn't quite figure out), so making it smaller wouldn't entirely avoid the issue. idk though.

It is a server wide setting though, so you're right it would affect OCR stuff in other interviews. I can see if it negatively affects some sample docs

**Closed** 2023-08-29 14:22 UTC

**Comment by nonprofittechy** [comment] 2023-08-29 14:26
Just to add a small note -- switching to JPEG would reduce file size but would likely have a small negative impact (unless there's some hardware acceleration) on performance because it is a compressed format. Image quality would also suffer.

Looks like if we dig into this more, we should see if it's possible to separate the code that generates thumbnails, which needs a very low quality render, from the code that enables OCRing of documents.

Or encourage Docsasemble to use OCRMyPDF natively, which is definitely faster than the built-in OCR method.

**Comment by BryceStevenWilley** [comment] 2023-08-29 14:34
>

**Comment by BryceStevenWilley** [comment] 2023-08-29 14:51
I changed `png resolution` on all of the servers to 200.

> Looks like if we dig into this more, we should see if it's possible to separate the code that generates thumbnails, which needs a very low quality render, from the code that enables OCRing of documents.

Since I've already done this digging; there are 3 use cases here; thumbnails, rendering in a document at what I'd consider "human" high quality, and the OCR renderings.  Right now there's only "screen", which defaults to 75 DPI, and "page", which defaults to 300 DPI (both are customizable in the config). It might be possible to split out "page" into "page" and "ocr". IMO we could also stand to reduce the resolution of "screen"; the example I've been using generates at 3024 by 4032, but only displays at max 900 by 1200 on my biggest screen (and on our thumbnail page, is only 240 by 320).

> encourage Docsasemble to use OCRMyPDF natively, which is definitely faster than the built-in OCR method.

We can still do this, but it doesn't solve this root cause, where there was no OCR.

**Comment by nonprofittechy** [comment] 2023-08-29 15:36
> We can still do this, but it doesn't solve this root cause, where there was no OCR.

Good point--I was thinking general DA optimization around PDF->image when I mentioned the OCR.

**Comment by BryceStevenWilley** [comment] 2023-08-30 20:50
Some additional information for this issue: the upload PDF that was causing all of this had dimensions of 42 by 56 inches, much larger than most PDFs that we receive, and almost certainly why this PDF in particular was causing issues with DPI scaling.

I'm now thinking that maybe a variable DPI based on document height is a good idea, but feels like a fairly big feature that I can't put effort into at the moment.

**Comment by nonprofittechy** [comment] 2023-08-30 20:57
I'm assuming the PDF was created by taking a photo, does that seem right, or do we think the user literally uploaded the pdf?

If so perhaps we need to look at frontend code to adjust how the file upload comes across. Perhaps it varies by browser or device.

**Comment by BryceStevenWilley** [comment] 2023-08-30 21:13
> I'm assuming the PDF was created by taking a photo, does that seem right, or do we think the user literally uploaded the pdf?

They uploaded the PDF. It's a PDF where the only content is a picture, but they did create the PDF; it was made a few hours before the submission, PDF 1.3, and the producer is "iOS Version (removed specific version numbers here)... Quartz PDFContext".

So, unlikely to always happen, but we should be resilient to large PDFs like this.

**Comment by aidanielson** [comment] 2023-10-12 14:32
Just fyi as to the "why would the PDF be 42, 52 whatever inches" above, in my case, I was tinkering with image preprocessing, specifically upscaling the document to meet a particular text x-height to maximize ocr accuracy. In doing so, the resultant PDF ended up like 49 inches or something ridiculous. So that's a possible cause/reason for the sizing anomaly.
